theme: jekyll-theme-primer
title: dzirtusss (aka Sergey Tarasov)
description: just a personal blog
url: "https://dzirtusss.com"
author: dzitusss
logo: /assets/header.jpg

plugins:
  - jemoji
  # - jekyll-avatar
  - jekyll-seo-tag
  - jekyll-sitemap # position is important

permalink: /:categories/:title

exclude:
  - scripts
  - Gemfile
  - Gemfile.lock
  - Rakefile
